# Permalinks
permalink:           pretty

# Setup
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               'Álgebra Lineal I'
tagline:             'Semestre 2020-2'
description:         ''
url:                 ''
baseurl:             '/algebra_lineal_I'

# About/contact
author:
  name:              'Víctor Augusto Samayoa Donado'
  url:               ''
  email:             'vasamayoa+algebra_lineal_I_2020-2@ciencias.unam.mx'

# Custom vars
version:             1.1.0
